
CREATE TABLE client (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(40) DEFAULT NULL,
	last_name VARCHAR(40) DEFAULT NULL,
	patronnymic VARCHAR(40) DEFAULT NULL,
	phone VARCHAR(40) DEFAULT NULL
);  

CREATE TABLE mechanic (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(40) DEFAULT NULL,
	last_name VARCHAR(40) DEFAULT NULL,
	wages DECIMAL(12,2) DEFAULT NULL,
	phone VARCHAR(40) DEFAULT NULL
);  

CREATE TABLE orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description VARCHAR(5000) DEFAULT NULL,
	client_id BIGINT DEFAULT NULL,
	mechanic_id BIGINT DEFAULT NULL,
	status VARCHAR(50) DEFAULT NULL,
	date_creat TIMESTAMP DEFAULT NULL,
	completion_date TIMESTAMP DEFAULT NULL,
	price DECIMAL(12,2) DEFAULT NULL,
	FOREIGN KEY (client_id) REFERENCES client(id),
	FOREIGN KEY (mechanic_id) REFERENCES mechanic(id)
);  

INSERT INTO client (first_name, last_name, patronnymic, phone)
VALUES ('Сидоров', 'Сидор', 'Сидорович', '+7(311)311-11-11');
INSERT INTO client (first_name, last_name, patronnymic, phone)
VALUES ('Петров', 'Петр', 'Петрович', '+7(311)322-22-21');
INSERT INTO client (first_name, last_name, patronnymic, phone)
VALUES ('Иванов', 'Иван', 'Иванович', '+7(311)525-25-21');
INSERT INTO client (first_name, last_name, patronnymic, phone)
VALUES ('Максимов', 'Максим', 'Максимович', '+7(311)22-55-99');
INSERT INTO client (first_name, last_name, patronnymic, phone)
VALUES ('Федоров', 'Федор', 'Федорович', '+7(311)337-77-77');

INSERT INTO mechanic (first_name, last_name, patronnymic, wages, phone)
VALUES ('Сидоров', 'Сидор', 'Сидорович', '+7(311)311-11-11');
INSERT INTO mechanic (first_name, last_name, patronnymic, wages, phone)
VALUES ('Петров', 'Петр', 'Петрович', '+7(311)322-22-21');



SHUTDOWN;